// <auto-generated />
using HW_8;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW_8.Migrations
{
    [DbContext(typeof(CarAdvancedContext))]
    [Migration("20210218070257_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW_8.models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "My car audi",
                            FirstName = "Vadim",
                            LastName = "Dubovskiy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "My car audi",
                            FirstName = "Vadim",
                            LastName = "Dubovskiy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "My car audi",
                            FirstName = "Vadim",
                            LastName = "Dubovskiy"
                        });
                });

            modelBuilder.Entity("HW_8.models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorID = 1,
                            CarName = "Audi",
                            Color = "green",
                            ModelName = "80",
                            Year = 35
                        },
                        new
                        {
                            Id = 2,
                            AuthorID = 2,
                            CarName = "Opel",
                            Color = "blue",
                            ModelName = "astra",
                            Year = 35
                        },
                        new
                        {
                            Id = 3,
                            AuthorID = 3,
                            CarName = "Audi",
                            Color = "green",
                            ModelName = "80",
                            Year = 35
                        });
                });

            modelBuilder.Entity("HW_8.models.Car", b =>
                {
                    b.HasOne("HW_8.models.Author", "Author")
                        .WithMany("Cars")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HW_8.models.Author", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
